language: node_js
node_js:
  - "10"
before_script:
  - npm run build
before_deploy:
  - git config --local user.name "William Wong"
  - git config --local user.email "compulim@hotmail.com"
  - npx version-from-git --travis
deploy:
  - provider: npm
    api_key:
      secure: "m7zVRr/h3RgtgPyME2eWlzECQ1ogR6fRuyXK2G7lpOUl9kN0OoohWnjQ1NZ4I0+C0jZPdoGxa3m06WjW3F3YmK2JwdJUAlcy3jK4d8U3oqdpOfIRxx+e3pUwVveT7324I8tDlWd7tlIbEwTpy+x7+aKctEXqS3hAltmFHO+gbWPh5agCm6wneN/ohB1h1LtE0wdeK2jmr/ZLwvP92r1x2IheISxFMNjJahnZ/yZm8+PHFfmMdnozX2eCKiYwSG/CV1C36DKujP56QIA26la7O4GoMxomuU4Fh9aTFb6h/FgZeee9lqyK1JysRmV4HJvqxgbrhN6Bv3tiRk8FA2Fut+UjVunU06eMm59PoplC62CChf575zyEbFKXYaJcUh4hwcGJ190PHA6zbhgxSBAnXfTNXMkn4X9wduW8eTHDH/q45j+OKAMyka4o6SPsIiCr5jRTqSu7XjX5x+2w5jy9Hj1CzaokzCViCWoROxx6jzoDxVqI0laTpr5g0sXq17uJdA79uHMvmysIrwq4dYR6xNDys3nJDuTcitbOAAXc/sqGwRwd+j5KwsnSDm2wTeka9mtmvdG0lwGbzdwcVuCcLI1rRCHJyMMSBMA562pzN69/TavIsx8Gud75v5MF4K/hd3CNB0kCRWgfTsd6hA1vozKGJW11UCPgWdUZ10EAfPc="
    email: "compulim@hotmail.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "m7zVRr/h3RgtgPyME2eWlzECQ1ogR6fRuyXK2G7lpOUl9kN0OoohWnjQ1NZ4I0+C0jZPdoGxa3m06WjW3F3YmK2JwdJUAlcy3jK4d8U3oqdpOfIRxx+e3pUwVveT7324I8tDlWd7tlIbEwTpy+x7+aKctEXqS3hAltmFHO+gbWPh5agCm6wneN/ohB1h1LtE0wdeK2jmr/ZLwvP92r1x2IheISxFMNjJahnZ/yZm8+PHFfmMdnozX2eCKiYwSG/CV1C36DKujP56QIA26la7O4GoMxomuU4Fh9aTFb6h/FgZeee9lqyK1JysRmV4HJvqxgbrhN6Bv3tiRk8FA2Fut+UjVunU06eMm59PoplC62CChf575zyEbFKXYaJcUh4hwcGJ190PHA6zbhgxSBAnXfTNXMkn4X9wduW8eTHDH/q45j+OKAMyka4o6SPsIiCr5jRTqSu7XjX5x+2w5jy9Hj1CzaokzCViCWoROxx6jzoDxVqI0laTpr5g0sXq17uJdA79uHMvmysIrwq4dYR6xNDys3nJDuTcitbOAAXc/sqGwRwd+j5KwsnSDm2wTeka9mtmvdG0lwGbzdwcVuCcLI1rRCHJyMMSBMA562pzN69/TavIsx8Gud75v5MF4K/hd3CNB0kCRWgfTsd6hA1vozKGJW11UCPgWdUZ10EAfPc="
    email: "compulim@hotmail.com"
    on:
      tags: true
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: "aoeHl6dyhUWCA+UToMI9TdafaxDXDfS0D1lMoTlobVdDxvUs+9m9QFtgPLQMAZp5NOpCHCTDeePHCWXum0xcw6fbnQUUAxtKyGIZoM21wKgGXICr2MiyQmaiSAMRM5P5+K+Ds1CaARL6XxWGZsEpPMNB8btAW20fKHbR99vGQ0etSJBIPgeSNy1KNYT6jnuEyxzJ6jVi0bhvGSHuTpF9wqqq4GsqlyPOOWXKs/fFkQwsII/odP/usmRpHGY5IrzIrw5mVJbcFB9VCHGQYGNB87OtexsyEqJ0C3ohXeuoaRkvDNoxcRjupYJuoMNkwqrrTgp7HYZST+/E8u3dd0llEERQmH9aq5GpPD8BUxQXSQ5stMnQcpHb3gJYPUmE9kqBs8R1dRFMsS6mmTAQPPK03yiTiZjDRRh+XT94DdyNirKhaopNghklakHbykyKEuRxlFSM1RYlXCjEmOb4tXprHhvicUYnmXUEmn886lb7bVoqkOpYssSTv/5DH1PVxfyZUbmC3LvJjv8edsHKSEkoeQVFEblpTDUvhHSueSybwRkBGaEhlE3U+qYJ6s5isKejZeNMWYIKfP3O47BhADD7DvOoATUzpJ5xR+i09eH0iMj9j6HNBVALujA7VmP7b41Bnd5nxTloRUd/2Vptv6bMl12yDZuwnx7P8yhL1nTDpBI="
    on:
      tags: true
    skip_cleanup: true
