language: node_js
node_js:
  - "10"
before_script:
  - npm run build
before_deploy:
  - git config --local user.name "William Wong"
  - git config --local user.email "compulim@hotmail.com"
  - npx version-from-git --travis
deploy:
  - provider: npm
    api_key:
      secure: "PdWgjIleA2XpsPmwGO3mDFhy3wtcOZ8QnMZYlsn4XYqPk95gyYggRdT6h2H+e0eweLADknJQ/xfcdUuQmJXk7Gfr/4sS26LbS+eJfqJ9FRRl6aOK9gvqgCDagGvUoKfMY5GZCJUdFvHsRTgyg5ueiod+Fa+DJ2Y+jlZf8GQ3VMUOfsbQlaxRpIcc0+Hl+aGwKyd7L4XXIOM0sQrgF5atcQtXW9kDnrCRkKmJ1El6TA/3jxk69ROLOLTkhaL2T5rQY+oVRmgoGSV0j4Om3lwuRgY38Z7yhswLEsHA/0EK9qmTRrRfWVGWUfYjrdD2M/St9gip+x9IRprLwHgfgUDNhuVgTGlhYl8GQQUNkEkLqTAEsy2tRZx2TYFfjxX4hjOBFmPZDjSS/G9RAju1+sJekVWepD5PwdBQxbR3uyWbg2/N8/7e/DVvLct7/0ah+fr/VxW1Q8PC49ZkCu68/uBAHFkPXFCWzNDdmV4G5QfFs0aY3iEbxbvXC+tzwepysId9fNgC8pyVL0ti4SCT4Wj+N/JPL5FDj0ATUJdcvxeCRsqTDXkKu8UOuuG0vYwdNC1UYrkvLr6lN1K0ilGTUb736BwfQkg8DvtU9TNZCLmcr0QbGqTsAKgQCUDUJe74ld+PtDKflwvbB2dIQEjopRgWqVIvh3p74dTanilXW996hCw="
    email: "compulim@hotmail.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "PdWgjIleA2XpsPmwGO3mDFhy3wtcOZ8QnMZYlsn4XYqPk95gyYggRdT6h2H+e0eweLADknJQ/xfcdUuQmJXk7Gfr/4sS26LbS+eJfqJ9FRRl6aOK9gvqgCDagGvUoKfMY5GZCJUdFvHsRTgyg5ueiod+Fa+DJ2Y+jlZf8GQ3VMUOfsbQlaxRpIcc0+Hl+aGwKyd7L4XXIOM0sQrgF5atcQtXW9kDnrCRkKmJ1El6TA/3jxk69ROLOLTkhaL2T5rQY+oVRmgoGSV0j4Om3lwuRgY38Z7yhswLEsHA/0EK9qmTRrRfWVGWUfYjrdD2M/St9gip+x9IRprLwHgfgUDNhuVgTGlhYl8GQQUNkEkLqTAEsy2tRZx2TYFfjxX4hjOBFmPZDjSS/G9RAju1+sJekVWepD5PwdBQxbR3uyWbg2/N8/7e/DVvLct7/0ah+fr/VxW1Q8PC49ZkCu68/uBAHFkPXFCWzNDdmV4G5QfFs0aY3iEbxbvXC+tzwepysId9fNgC8pyVL0ti4SCT4Wj+N/JPL5FDj0ATUJdcvxeCRsqTDXkKu8UOuuG0vYwdNC1UYrkvLr6lN1K0ilGTUb736BwfQkg8DvtU9TNZCLmcr0QbGqTsAKgQCUDUJe74ld+PtDKflwvbB2dIQEjopRgWqVIvh3p74dTanilXW996hCw="
    email: "compulim@hotmail.com"
    on:
      tags: true
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: "aoeHl6dyhUWCA+UToMI9TdafaxDXDfS0D1lMoTlobVdDxvUs+9m9QFtgPLQMAZp5NOpCHCTDeePHCWXum0xcw6fbnQUUAxtKyGIZoM21wKgGXICr2MiyQmaiSAMRM5P5+K+Ds1CaARL6XxWGZsEpPMNB8btAW20fKHbR99vGQ0etSJBIPgeSNy1KNYT6jnuEyxzJ6jVi0bhvGSHuTpF9wqqq4GsqlyPOOWXKs/fFkQwsII/odP/usmRpHGY5IrzIrw5mVJbcFB9VCHGQYGNB87OtexsyEqJ0C3ohXeuoaRkvDNoxcRjupYJuoMNkwqrrTgp7HYZST+/E8u3dd0llEERQmH9aq5GpPD8BUxQXSQ5stMnQcpHb3gJYPUmE9kqBs8R1dRFMsS6mmTAQPPK03yiTiZjDRRh+XT94DdyNirKhaopNghklakHbykyKEuRxlFSM1RYlXCjEmOb4tXprHhvicUYnmXUEmn886lb7bVoqkOpYssSTv/5DH1PVxfyZUbmC3LvJjv8edsHKSEkoeQVFEblpTDUvhHSueSybwRkBGaEhlE3U+qYJ6s5isKejZeNMWYIKfP3O47BhADD7DvOoATUzpJ5xR+i09eH0iMj9j6HNBVALujA7VmP7b41Bnd5nxTloRUd/2Vptv6bMl12yDZuwnx7P8yhL1nTDpBI="
    on:
      tags: true
    skip_cleanup: true
